Feat: Our values
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #21
Opened 2021-07-24 12:19 UTC by MiraMC149

This is the values banner you requested

2021-07-25 08:38 UTC, osamaakb requested changes
**Please**, stick to the technical manual and follow the instructions there regarding the folders structure

2021-07-25 08:38 UTC, osamaakb commented on src/components/Consume.jsx
> +      <svg
please move `SVGs` to a separate file

2021-07-25 08:38 UTC, osamaakb commented on src/components/Donate.jsx
> +        {" "}
remove this `{" "}`

2021-07-25 08:38 UTC, osamaakb commented on src/components/Donate.jsx
> +      <svg
same here

2021-07-25 08:38 UTC, osamaakb commented on src/components/Planet.jsx
> +        {" "}
same here and everywhere else

2021-07-25 08:38 UTC, osamaakb commented on src/components/Awarness.jsx
> +function Awarness() {
is this an icon or a component?

2021-07-26 08:58 UTC, osamaakb commented
same here, you have some conflicts to fix

2021-07-26 09:00 UTC, osamaakb requested changes
otherwise looks good, just add more padding at the bottom, it doesn't match the one on top

![image](https://user-images.githubusercontent.com/12795240/126962915-7a938c4a-704c-4492-b768-00c5088b6396.png)

2021-07-27 13:47 UTC, osamaakb requested changes

2021-07-27 13:47 UTC, osamaakb commented on src/components/OurValues/OurValues.jsx
> +      <div className="flex flex-col mr-60 mt-20 ">
you shouldn't add margin-right to each item to make them look like a grid, you can achieve that using flex-box wrap and add space between flex item.

read here
https://css-tricks.com/dont-overthink-flexbox-grids/

and here
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

2021-07-29 15:25 UTC, MiraMC149 commented
I finally managed to resolve the issues

2021-07-30 15:36 UTC, osamaakb approved these changes
Good job @MiraMC149

2021-07-30 15:36 UTC, merged