Aboutpageheader
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #33
Opened 2021-07-29 13:56 UTC by marwaghassa

This resolve issue #10

2021-07-30 15:39 UTC, osamaakb requested changes
you have a lot of image files, what are they about? you only need one image

2021-07-30 15:39 UTC, osamaakb commented on src/App.js
> +      <Aboutpageheader />
what did we say about not changing the `app.js`?

2021-07-30 15:39 UTC, osamaakb commented on src/components/aboutpageheader/aboutpageheader.jsx
> +function Aboutpageheader() {
the component, file and folder names aren't correct please fix them it should be `AboutPageHeader` for all of them

2021-07-30 15:39 UTC, osamaakb commented on tailwind.config.js
> +      about:"#892E2E",
this color name doesn't make sense

2021-07-30 22:32 UTC, marwaghassa commented
Requested changes done .

2021-07-31 20:32 UTC, osamaakb approved these changes

2021-07-31 20:32 UTC, merged