Home page headerr
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #36
Opened 2021-07-31 12:12 UTC by marwaghassa

New Home page header branch resolving issue #1

2021-07-31 12:42 UTC, ziadbaroudi requested changes

2021-07-31 12:42 UTC, ziadbaroudi commented on tailwind.config.js
> +        xl: "-40px -35px #7EAC8A",
changing xl values will cause problems in other components, please don't override existing values, instead create a new one with a different name, xxl for example. 
Component using xl: cart-item.

2021-08-01 11:05 UTC, osamaakb requested changes
it doesn't look like the figma design,

![image](https://user-images.githubusercontent.com/12795240/127768516-a47bd0eb-ae42-4a4c-8a20-b6039eef385a.png)

2021-08-03 10:25 UTC, osamaakb commented
Will close this for now

2021-08-14 10:32 UTC, marwaghassa commented
Home Page Header styled

2021-08-16 09:34 UTC, osamaakb commented
please resolve the conflicts first

2021-08-16 19:51 UTC, osamaakb commented
it is still not 100% like figma, but good job @marwaghassa , I will merge it for the sake of time

2021-08-16 19:51 UTC, osamaakb approved these changes

2021-08-16 19:52 UTC, merged