feat: change the way you shop banner
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #39
Opened 2021-08-01 16:24 UTC by MiraMC149

![Screenshot (1204)](https://user-images.githubusercontent.com/81479191/127777169-3d960a1b-9c58-443d-a938-17ddc6519f2a.png)
![Screenshot (1205)](https://user-images.githubusercontent.com/81479191/127777180-a5d0b767-7baa-451e-ba3b-ab0c1d1b2510.png)
This banner is in the contact page, it's very big so it didn't fit in one screenshot

2021-08-02 09:00 UTC, osamaakb requested changes
can you make the image smaller, like 50% smaller, and center it so it doesn't take the entire screen, that may be a bit confusing for the user experience

2021-08-02 20:51 UTC, MiraMC149 commented
![Screenshot (1206)](https://user-images.githubusercontent.com/81479191/127922139-2f1ed201-d764-48bd-af87-5c532e5f14d5.png)
Is this better?

2021-08-03 10:38 UTC, osamaakb commented
way better, good job @MiraMC149

2021-08-03 10:38 UTC, osamaakb approved these changes

2021-08-03 10:38 UTC, merged