Feat: About us page
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #51
Opened 2021-08-05 19:38 UTC by MiraMC149

this is the about us page but without the modal and I'm not sure if I added it to the router correctly
![Screenshot (1233)](https://user-images.githubusercontent.com/81479191/128409902-b7f1fc9d-a61e-4b38-9a10-7fa8ef0b499a.png)
![Screenshot (1234)](https://user-images.githubusercontent.com/81479191/128409959-fa65b4fe-d78a-4276-9143-93227146dfcd.png)
![Screenshot (1235)](https://user-images.githubusercontent.com/81479191/128409971-55bff46c-f9ee-4ead-bd37-a9cde446d474.png)
![Screenshot (1236)](https://user-images.githubusercontent.com/81479191/128409980-8860e145-7b5f-4570-9513-c954d311089c.png)
![Screenshot (1237)](https://user-images.githubusercontent.com/81479191/128409988-3ea23ae4-c2a0-4bae-8ac1-f526bc5cacf8.png)

2021-08-07 17:22 UTC, osamaakb requested changes
Good job @MiraMC149

2021-08-07 17:22 UTC, osamaakb commented on src/App.js
> +      <About />
you don't need this one just the one in the switch

2021-08-07 17:22 UTC, osamaakb commented on src/components/TeamMemberCard/Member1.jsx
> +function Member1() {
replace the names in real members names like `MiraPhoto`

2021-08-08 11:04 UTC, osamaakb requested changes
Please pay more attention to the code and the output before submitting,

the `keep in touch` button should be under the team members and it should have some text maybe above it says `if you want more information about us` and then the button or something similar to make it more friendly
![image](https://user-images.githubusercontent.com/12795240/128629838-a93a3676-6197-4639-8e82-3cf71e9f5530.png)

2021-08-08 11:04 UTC, osamaakb commented on src/pages/About/About.jsx
> +      <Navbar />
why the Navbar and Footer are here if they are in the `app.js` already?

2021-08-08 11:04 UTC, osamaakb commented on src/App.js
>        <Footer />
the footer should be under everything that is why it is called `Footer` (:

2021-08-09 10:48 UTC, MiraMC149 commented
![ezgif com-gif-maker](https://user-images.githubusercontent.com/81479191/128695361-36e34c96-e2b8-426b-91d3-88d805c81c7e.gif)
This is a preview of the modal

2021-08-09 12:18 UTC, osamaakb approved these changes

2021-08-09 12:18 UTC, merged