Feat: Contact us modal
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #52
Opened 2021-08-06 19:45 UTC by marwaghassa

This resolve issue #32 
(Modal done without background design)

2021-08-07 17:19 UTC, osamaakb requested changes
Good job @marwaghassa , only few changes required

2021-08-07 17:19 UTC, osamaakb commented on src/App.js
> +     <ContactUsModel open={open} setOpen={setOpen} />
Give this code to @MiraMC149 , as she is the one will be calling the modal from her about page and remove it from here in the `app.js`

2021-08-07 17:19 UTC, osamaakb commented on src/components/contactUsModel/contactUsModel.jsx
> +
format the code in this file using `yarn format`

2021-08-08 11:06 UTC, osamaakb requested changes
please solve the conflicts + the comments below

2021-08-08 11:06 UTC, osamaakb commented on src/App.js
> +import React, { useState } from "react";
why you need `useState` here?

2021-08-08 11:06 UTC, osamaakb commented on package.json
> +    "@afc-org/react-tailwind": "^0.1.1",
what is this library exactly do for you here? as I see you are using the modal from `headlessui` library

2021-08-08 21:30 UTC, marwaghassa commented
![Screenshot (19)](https://user-images.githubusercontent.com/81817432/128646297-39bccd00-6a47-4cfa-936a-34290be3e2e5.png)

2021-08-09 12:19 UTC, osamaakb reviewed
Good job @marwaghassa , I merged it from Mira's about us page PR, so I will close this

2021-08-09 12:19 UTC, closed without merging