Home page
Lebanon-02-WBC-Capstones/shop-from-nature-web pull request #69
Opened 2021-08-10 19:34 UTC by ziadbaroudi

2021-08-11 10:35 UTC, osamaakb requested changes
I got these errors! I will fix them but you should of paid more attention to these errors before submitting

![image](https://user-images.githubusercontent.com/12795240/129014796-cbf98646-394a-4ae2-990b-61bbbc64eb58.png)

2021-08-11 10:58 UTC, osamaakb requested changes
I ran the app and there are few UI changes required, please pay more attention to the figma design before submitting the work:
- add more space around the recent blogs
![image](https://user-images.githubusercontent.com/12795240/129017475-d79bf73e-d02f-46b3-a977-0965c4f99569.png)

- make the arrival items cards slide, add more space to the left and right
![image](https://user-images.githubusercontent.com/12795240/129017646-1a045f15-7237-44d3-aa14-2e91f83dff18.png)

- add the NewsLetter component under the recent blogs

2021-08-11 15:22 UTC, ziadbaroudi commented
![image](https://user-images.githubusercontent.com/69876518/129055896-2f913fcd-b272-4b59-908c-64f28e791e5e.png)
![image](https://user-images.githubusercontent.com/69876518/129055944-9b6ee382-f1f5-40f1-a9f0-79cfa729e7f6.png)

2021-08-14 07:54 UTC, osamaakb approved these changes

2021-08-14 07:54 UTC, merged